/*
 * DataAnalyserAboutBox.java
 */

package com.mu.stock.ui;

import com.mu.stock.entity.Account;
import com.mu.stock.entity.Company;
import com.mu.stock.entity.TxnLog;
import com.mu.util.MathUtil;
import java.util.ArrayList;
import org.jdesktop.application.Action;

public class BuySellView extends javax.swing.JDialog {

    public BuySellView(java.awt.Frame parent, AccountTxnView acctTxnView, Account acct, Company c, String action, String price) {
        super(parent);
        initComponents();
        init(acctTxnView, acct, c, action, price);
    }

    @Action public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCpy = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        lblAction = new javax.swing.JLabel();
        lblCpy = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblNow = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAfter = new javax.swing.JLabel();
        lblPerc = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblBullet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.mu.stock.ui.DataAnalyserApp.class).getContext().getResourceMap(BuySellView.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setName("BuySell"); // NOI18N

        lbCpy.setText(resourceMap.getString("lbCpy.text")); // NOI18N
        lbCpy.setName("lbCpy"); // NOI18N

        btnSubmit.setText(resourceMap.getString("btnSubmit.text")); // NOI18N
        btnSubmit.setName("btnSubmit"); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        tfAmount.setText(resourceMap.getString("tfAmount.text")); // NOI18N
        tfAmount.setName("tfAmount"); // NOI18N
        tfAmount.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                tfAmountMouseWheelMoved(evt);
            }
        });
        tfAmount.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfAmountPropertyChange(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        tfPrice.setText(resourceMap.getString("tfPrice.text")); // NOI18N
        tfPrice.setName("tfPrice"); // NOI18N
        tfPrice.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                tfPriceMouseWheelMoved(evt);
            }
        });
        tfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPriceActionPerformed(evt);
            }
        });

        lblAction.setText(resourceMap.getString("lblAction.text")); // NOI18N
        lblAction.setName("lblAction"); // NOI18N

        lblCpy.setText(resourceMap.getString("lblCpy.text")); // NOI18N
        lblCpy.setName("lblCpy"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        lblTotal.setText(resourceMap.getString("lblTotal.text")); // NOI18N
        lblTotal.setName("lblTotal"); // NOI18N

        lblNow.setText(resourceMap.getString("lblNow.text")); // NOI18N
        lblNow.setName("lblNow"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        lblAfter.setText(resourceMap.getString("lblAfter.text")); // NOI18N
        lblAfter.setName("lblAfter"); // NOI18N

        lblPerc.setText(resourceMap.getString("lblPerc.text")); // NOI18N
        lblPerc.setName("lblPerc"); // NOI18N

        jLabel7.setName("jLabel7"); // NOI18N

        lblBullet.setText(resourceMap.getString("lblBullet.text")); // NOI18N
        lblBullet.setName("lblBullet"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCpy, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNow, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addGap(232, 232, 232))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCpy)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                        .addComponent(tfAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                                    .addComponent(lblAction))
                                .addContainerGap(166, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAfter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPerc, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                .addGap(67, 67, 67))
                                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                                        .addGap(2, 2, 2)
                                        .addComponent(lblBullet, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                                .addGap(51, 51, 51))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubmit)
                        .addContainerGap(284, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCpy, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCpy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel2)
                    .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel3)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblPerc)
                    .addComponent(lblBullet))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblNow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblAfter, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSubmitActionPerformed
    {//GEN-HEADEREND:event_btnSubmitActionPerformed
        acct.submitTxn(company, action, Integer.valueOf(tfAmount.getText()), Float.valueOf(tfPrice.getText()));
        acctTxnView.initTxnTab();
        dispose();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void tfPriceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfPriceActionPerformed
    {//GEN-HEADEREND:event_tfPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPriceActionPerformed

    private void tfAmountMouseWheelMoved(java.awt.event.MouseWheelEvent evt)//GEN-FIRST:event_tfAmountMouseWheelMoved
    {//GEN-HEADEREND:event_tfAmountMouseWheelMoved
        if(evt.getScrollType()==java.awt.event.MouseWheelEvent.WHEEL_UNIT_SCROLL)
        {
            int i = (-1)*evt.getUnitsToScroll()/evt.getScrollAmount();
            int now = Integer.valueOf(tfAmount.getText());
            int fact = now/100;
            if(fact<1)
                fact = 1;
            now += i*fact;
            tfAmount.setText(now+"");
        }
        updateLabels();
    }//GEN-LAST:event_tfAmountMouseWheelMoved

    private void tfPriceMouseWheelMoved(java.awt.event.MouseWheelEvent evt)//GEN-FIRST:event_tfPriceMouseWheelMoved
    {//GEN-HEADEREND:event_tfPriceMouseWheelMoved
        if(evt.getScrollType()==java.awt.event.MouseWheelEvent.WHEEL_UNIT_SCROLL)
        {
            int i = (-1)*evt.getUnitsToScroll()/evt.getScrollAmount();
            float now = Float.valueOf(tfPrice.getText());
            float fact = now/100;
            if(fact<0.001)
                fact = 0.001F;
            now += i*fact;
            tfPrice.setText(MathUtil.round(now, 3)+"");
        }
        updateLabels();
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPriceMouseWheelMoved

    private void tfAmountPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_tfAmountPropertyChange
    {//GEN-HEADEREND:event_tfAmountPropertyChange
        if(!tfPrice.getText().isEmpty()&&!tfAmount.getText().isEmpty())
            updateLabels();
    }//GEN-LAST:event_tfAmountPropertyChange
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbCpy;
    private javax.swing.JLabel lblAction;
    private javax.swing.JLabel lblAfter;
    private javax.swing.JLabel lblBullet;
    private javax.swing.JLabel lblCpy;
    private javax.swing.JLabel lblNow;
    private javax.swing.JLabel lblPerc;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField tfAmount;
    private javax.swing.JTextField tfPrice;
    // End of variables declaration//GEN-END:variables
    private Account acct;
    private Company company;
    private String action;
    private AccountTxnView acctTxnView;

    public void init(AccountTxnView acctTxnView, Account acct, Company c, String action, String price)
    {
        this.acct = acct;
        this.company = c;
        this.action = action;
        this.acctTxnView = acctTxnView;
        lblAction.setText(action);
        lblCpy.setText(c.getShortName());
        tfPrice.setText(price);
        tfAmount.setText((int)(10000/Float.valueOf(price))+"");
        lblNow.setText(acct.getCash().intValue()+"");
        updateLabels();

    }
    private void updateLabels()
    {
        float p = Float.valueOf(tfPrice.getText());
        int amt = Integer.valueOf(tfAmount.getText());
        float t = p*amt;
        float af = acct.getCash() + p*amt*(action.equals(TxnLog.Buy)? -1 : 1);
        int curAmt = 0;
        ArrayList al = acct.getPortfolio().get(company);
        if(al != null)
        {
            curAmt = (Integer)al.get(0);
        }
        int afAmt = curAmt + amt*(action.equals(TxnLog.Buy)? -1 : 1);

        lblBullet.setText((int)(t/10000)+ " Bullets");
        lblPerc.setText(MathUtil.round(t*100/acct.getCash(), 1)+"%");
        lblTotal.setText((int)t+"");
        lblAfter.setText(String.format("Cash:%d, Shares:%d",(int)af,afAmt));
    }
}
